---
Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: ranveerCluster
      Version: "1.25"
      RoleArn: arn:aws:iam::388328004932:role/AWSEKSRole
      ResourcesVpcConfig:
        SecurityGroupIds:
          - sg-0d8315f2e7a43714e
        SubnetIds:
          - subnet-0a31af885cfd8721d
          - subnet-01b356a04735bdf93
        EndpointPublicAccess: true
        EndpointPrivateAccess: false
        PublicAccessCidrs:
          - 0.0.0.0/0
  Nodegroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: ranveerEKS
      NodegroupName: ranveerNodegroup
      NodeRole: arn:aws:iam::388328004932:role/eks-node-group
      LaunchTemplate:
        Name: ranveerLaunch
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      Subnets:
        - subnet-0a31af885cfd8721d
        - subnet-01b356a04735bdf93
